import { createContext, useContext, useMemo, useState } from "react";

const LANG = createContext(null);

/** Simple farmer-first copy — Marathi default for Maharashtra UI */
export const STRINGS = {
  en: {
    brand: "Farm Genius",
    tagline: "Farm help for Maharashtra — six crops only",
    nav_dash: "Home",
    nav_disease: "Leaf doctor",
    nav_recommend: "Which crop fits?",
    nav_yield: "Yield idea",
    nav_market: "Sell / buy list",
    login_subtitle: "Your account stays on this browser until you leave.",
    nav_login: "Login",
    nav_logout: "Logout",
    nav_register: "Sign up",
    marathi_toggle: "मराठी",
    hero_sub:
      "Check leaves in easy words, note soil tests, estimate yield gently, watch today’s sky, meet buyers — Cotton, Sugarcane, Rice, Maize, Wheat, Soybean only.",
    hero_badge: "Maharashtra crops",
    home_leaf: "Leaf photo helper",
    home_leaf_hint: "One clear leaf photo • Marathi diagnosis & steps",
    home_soil: "Soil calculator",
    home_soil_hint: "Nutrients & moisture hints for your crop choice",
    home_yield: "Yield guess",
    home_yield_hint: "Rain & area idea — advisory only",
    home_market: "Local board",
    home_market_hint: "Farmers post price; dealers look",
    weather_title: "Today’s sky",
    weather_live: "Updated feed",
    weather_demo: "Sample forecast",
    weather_advice_label: "For your field today",
    weather_feels: "Feels like",
    weather_humidity: "Humidity",
    weather_wind: "Wind speed",
    weather_rain: "Rain next days (approx. mm/day)",
    weather_loading: "Loading weather…",
    loading: "Working on it…",
    upload_hint: "Choose a neat leaf photo (phone camera is OK)",
    disease_crop_label: "Which crop is this leaf from?",
    disease_crop_placeholder: "Select crop first",
    disease_crop_hint:
      "Choosing the right crop stops the tool from mixing rice, sugarcane, cotton, etc. — each crop only competes with its own diseases.",
    predict: "Show result",
    city: "Place",
    farmer: "Farmer",
    dealer: "Buyer / dealer",
    add_listing: "Add crop sale",
    buy_notice: "Dealers may call/message as you agree locally.",
    conf_bar: "How sure is the photo match",
    footer_line: "Only six crops for Maharashtra farms — still confirm every spray with local experts.",
    disease_note_jargon: "Uneven lighting or blurry leaves can confuse the photo check — sharp close-ups work best.",
    section_organic: "Organic / जैविक path",
    section_chemical: "Chemical path (authorised inputs)",
    section_now: "Do this right away",
    section_summary: "Short mix (Marathi-ready)",
    section_second: "Second possible match",
    improve_title: "How to make it sharper",
    low_confidence_banner: "Low confidence — verify below",
    top_three_title: "Other possibilities",
    dash_remind_1: "Leaf tool → double-check every spray with KVK / agri officer.",
    dash_remind_2: "Soil & yield tools give soft hints only — your soil card is final.",
    dash_remind_3: "Marketboard is for meeting people — price deal is between you two.",
    recommend_city: "District hub (weather)",
    recommend_steps_title: "Simple Marathi crop steps",
    recommend_detail:
      "Soil numbers from your card plus city for today’s sky. Only six Maharashtra crops appear — defer to soil tests and visits.",
    recommend_run: "Show matching crop ideas",
    yield_sale_band: "Rough sale ₹ range (farm gate style)",
    yield_per_ha: "Estimate per hectare (quintal)",
    yield_total_crop: "On your hectares",
    yield_detail:
      "Season rain, hectares, nutrients — yields are rough guesses; ₹ band uses example prices, not Mandi slips.",
    yield_run: "Show yield idea",
    yield_crop_label: "Pick crop",
    yield_forecast_words: "Guidance • check real mandi quotes",
    yield_heading_result: "Soft yield idea",
    yield_crop_word: "Crop",
  },
  mr: {
    brand: "फार्म जीनियस",
    tagline: "महाराष्ट्राच्या शेतकऱ्यांसाठी मदतची अ‍ॅप",
    nav_dash: "मुख्य पान",
    nav_disease: "पान डॉक्टर",
    nav_recommend: "कोणते पीक योग्य?",
    nav_yield: "उत्पादनचा अंदाज",
    nav_market: "विक्री / खरेदी फलक",
    login_subtitle: "आपोआप या ब्राउजरवर थांबेल — बाहेर पडला की पुन्हा लॉगिन करा.",
    nav_login: "लॉगिन",
    nav_logout: "बाहेर",
    nav_register: "नोंदणी",
    marathi_toggle: "English",
    hero_sub:
      "सोप्या भाषेत पानांची तपासणी; मातीची माहिती लिहून पीक सुचावा; पाऊस आणि क्षेत्रफळासह उत्पादनचा फक्त अंदाज; आजचे अद्याप हवामान; तुमच्या सहा पिकांखाली व्यापार — फक्त कापूस, ऊस, भात, मका, गहू, सोयाबीन.",
    hero_badge: "फक्त महाराष्ट्र पिकांचे फलक",
    home_leaf: "पानांचा फोटो तपास",
    home_leaf_hint: "एका स्पष्ट पान फोट्यावरून रोग आणि उपाय मराठीत",
    home_soil: "मातीचा हिशोब",
    home_soil_hint: "एनपीके, चू, ओलावा लिहून कोणते पीक बसेल ते करा",
    home_yield: "उत्पादन थोडक्यात अंदाज",
    home_yield_hint: "पाऊस + क्षेत्रफळ फक्त संकेतासाठी मदत करते",
    home_market: "बाजार पाटी",
    home_market_hint: "शेतकरीभाव लिहून ठेवा; व्यापारी पाहतात — नंतर व्यवहार तुम्हीच ठरवता",
    weather_title: "आजचे हवामान",
    weather_live: "नवीन माहिती",
    weather_demo: "नमुन्याचे अंदाज",
    weather_advice_label: "आज शेताच्या डोळ्यांना काय महत्त्वाचं",
    weather_feels: "जाणवत असलेला ताप",
    weather_humidity: "आर्द्रता",
    weather_wind: "वारा (मी/से)",
    weather_rain: "पुढचे दिवस — पाणी (अंदाजे मिमी दररोज)",
    weather_loading: "हवामान आणत आहोत…",
    loading: "काम होत आहे…",
    upload_hint: "पानांचा छान फोटो निवडा (मोबाईल कॅमेरा चालतो)",
    disease_crop_label: "हे पान कोणत्या पिकाचे आहे?",
    disease_crop_placeholder: "आधी पीक निवडा",
    disease_crop_hint:
      "बरोबर पीक निवडल्यावर भात / ऊस / कापूस इत्यादी रोग एकमेकांशी गोंधळणार नाहीत — फक्त त्या पिकाच्या रोगांशी तुलना होते.",
    predict: "निकाल दाखवा",
    city: "ठिकाण",
    farmer: "शेतकरी",
    dealer: "खरेदीदार / व्यापारी",
    add_listing: "विक्रीची नोंद",
    buy_notice: "व्यापारी फोन करतील असे स्थानिक करार तुम्हीच करा.",
    conf_bar: "फोटोशी एवढ्या टक्के जुळतंय",
    footer_line:
      "आम्ही फक्त या सहा महाराष्ट्र पिकांचा विचार करतो — फवाश्या आणि औषधे नेहमी तज्ज्ञांशी पुन्हा खात्री करा.",
    disease_note_jargon:
      "अंदाज फोट्यावरून घेतला जातो — अंधाराचा टिळका किंवा दूरचा फ्रेम चूक होऊ लागतो; पानावर जवळून स्पष्ट फोटो घ्या.",
    section_organic: "जैविक / नैसर्गिक उपाय",
    section_chemical: "अजैविक (अधिकृत रासायनिक) उपाय",
    section_now: "आत्ताच काय करावे लागेल?",
    section_summary: "थोडक्या शब्दांत उपचार",
    section_second: "इतरही शक्यता",
    improve_title: "नेमकेपण कसे वाढेल?",
    low_confidence_banner: "खात्री कमी — खाली तपासा",
    top_three_title: "इतर शक्यता",
    dash_remind_1: "पान तपासणी — फवाश्याचा निर्णय नेहमी केव्हीके / कृषी अधिकाऱ्याशी पुन्हा करा.",
    dash_remind_2: "माती व उत्पादन हिशोब फक्त मदत — शेवटचा निर्णय माती चाचणी व तज्ज्ञांवर.",
    dash_remind_3: "बाजार फलक म्हणजे ओळख — भावाचा तोडगा तुम्हीच व व्यापारीचा.",
    recommend_city: "जिल्ह्याच्या शहरासाठी हवामान",
    recommend_steps_title: "सोप्या मराठीत पीक पावले",
    recommend_detail:
      "मातीच्या चाचणीवरील आकडे आणि एक शहर निवडा — आजचे हवामानही सोप्या पावलांत जुळेल. फक्त महाराष्ट्राची सहा पिकेच — शेवटी माती तज्ज्ञांवर टाका.",
    recommend_run: "पिकाची सूचना पाहा",
    yield_sale_band: "उदाहरण भावांवरून एकूण विक्री रक्कम (आसपास ₹)",
    yield_per_ha: "प्रति हेक्टर उत्पादन (अंदाजे क्विंटल)",
    yield_total_crop: "तुमच्या क्षेत्रावर एकूण",
    yield_detail:
      "हंगामातील पाऊस मिमी, हेक्टर, खत — आकडा फक्त सल्ला; रुपयेही साध्या उदाहरण भावावर आहेत.",
    yield_run: "उत्पादन अंदाज शोधा",
    yield_crop_label: "पिक निवडा",
    yield_forecast_words: "फक्त निर्देश • खरी मंडीवर भाव घ्या",
    yield_heading_result: "उत्पादन अंदाजाचा थोडक्यात शब्दात आकडा",
    yield_crop_word: "पिक",
  },
};

export function LangProvider({ children }) {
  const [lang, setLang] = useState("mr");
  const value = useMemo(() => ({ lang, setLang, t: STRINGS[lang] }), [lang]);
  return <LANG.Provider value={value}>{children}</LANG.Provider>;
}

export function useLang() {
  const ctx = useContext(LANG);
  if (!ctx) throw new Error("useLang requires LangProvider");
  return ctx;
}
